image: testing
test:
  tags:
    - testing-docker
  script:
    - testing
  artifacts:
    paths: [report.txt.enc]
    when: always
rk_04:
  image: gcc
  stage: build
  only:
    - rk_04
  scrpit:
    - cd rk_04_AABD
    - make build
    - cat in.txt
    - make run
    - cat out.txt
