image: testing
test:
  tags:
    - testing-docker
  script:
    - testing
  artifacts:
    paths: [report.txt.enc]
    when: always
rk_01:
  image: frolvlad/alpine-gcc
  stage: build
  only:
      - rk_01
  script:
      - cd rk_01_01
      - gcc -Wall -Werror main.c
      - cd ../rk_01_02
      - gcc --std=c99 -Wall -Werror -Wfloat-equal -Wfloat-conversion -Wpedantic main.c
rk_03:
  image: gcc
  stage: build
  only:
      - rk_03
  script:
      - cd rk_03_04
      - make build
      - make run
